### PR TITLE
chore(qa): Skip WaitForQuayBuild stage for cdis-jenkins-lib PRs

### PR DESCRIPTION
**Pull request by themarcelor**
Erm.. yeah, that should work.

### CODE REVIEW

**Review by mfshao — APPROVED** [review]
💯

**Comment by paulineribeyre** [comment]
but then this step of the pipeline won't be tested so PRs that break it will pass jenkins :/ https://github.com/uc-cdis/cdis-jenkins-lib/blob/master/Dockerfile#L3

**Comment by mfshao** [comment]
I think it will only skip for the cdis-Jenkins-lib repo builds

**Comment by paulineribeyre** [comment]
right and the `waitForBuild` step is defined in `cdis-jenkins-lib`. so i can make any breaking change to the code for this step and it won't be detected

**Comment by paulineribeyre** [comment]
🤦

**Pull request merged**
