### PR TITLE
chore(git comment): post comment to git PR

### PR DESCRIPTION
**Pull request by frickjack**

### CODE REVIEW

**Comment by frickjack** [comment]
Hello from Atharva

**Comment by frickjack** [comment]
The time taken 29 min and counting

**Comment by frickjack** [comment]
3 : The time taken for Jenkins Build 12 sec and counting

**Comment by frickjack** [comment]
The time taken for Jenkins Build 4 : 11612 ms.

**Comment by frickjack** [comment]
The time taken for Jenkins Build 5 : 19652 ms.

**Comment by frickjack** [comment]
Jenkins Build 6 : time taken 41 sec ms.

**Comment by frickjack** [comment]
Jenkins Build 7 : time taken 39 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 8 : time taken 18 min

**Pull request merged**
